version: '3'

services:
    time-api:
        build: .
        hostname: api.time.docker
        working_dir: /var/www/html
        environment:
            DOCKER: ${DOCKER}
            DATABASE: ${DATABASE}
            ENVIRONMENT: ${ENVIRONMENT}
            XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
            XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
        ports:
            - 8081:80
        volumes:
            - ./api:/var/www/html
            - .data.db:/var/data.db
            - .vhost:/etc/apache2/sites-enabled/000-default.conf
